# Generated by Django 5.2.1 on 2025-05-15 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': ('Tipo de Veículo',), 'verbose_name_plural': 'Tipos de Veículos'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Placa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
